<a href="https://colab.research.google.com/github/noo-nine/Machine-Learning/blob/main/MultinomialNB_for_classifying_emails.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from google.colab import files
uploaded = files.upload()

Saving email.csv to email.csv


In [5]:
emails = pd.read_csv('email.csv')
emails.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
#data exploration
emails.duplicated().sum()

415

In [8]:
emails.drop_duplicates(inplace = True)

In [13]:
emails.isna().sum()

Category    0
Message     0
Spam        1
dtype: int64

In [10]:
emails.dtypes

Category    object
Message     object
dtype: object

In [14]:
emails.dropna(inplace = True)

In [15]:
# converting the category column to int datatype
emails['Spam'] = emails['Category'].map( {'spam' : 1, 'ham' : 0}).astype(int)
emails.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(emails['Message'], emails['Spam'], test_size = 0.3, random_state = 21)

In [22]:
# we need to convert messages to numbers
# we can use vectorizer for that
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x_train_vectorized = vectorizer.fit_transform(x_train.values)
print(vectorizer.get_feature_names_out())
#x_train_vectorized.toarray()

['00' '000' '000pes' ... 'zouk' 'zyada' '〨ud']


In [24]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_vectorized, y_train)

MultinomialNB()

In [25]:
# testing on test data
# vectorizing the test data
x_test_vectorized = vectorizer.transform(x_test)
model.predict(x_test_vectorized)

array([0, 0, 0, ..., 0, 1, 0])

In [26]:
model.score(x_test_vectorized, y_test)

0.9838501291989664

In [38]:
some_emails = [
    'Heyy, stop wasting your time on watching movies',
    'John, we noticed you are not taking advantage of your Dropbox account.',
    'Hey Karen, we havent seen you in a while and need to know if you are still interested in seeing emails from us.',
    'Elevate your date nights& make your movie sessions more special with Samsung!'
]

In [39]:
some_emails_vectorized = vectorizer.transform(some_emails)
model.predict(some_emails_vectorized)

array([0, 0, 0, 0])

# **Using Pipelines**

In [28]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('v', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [29]:
clf.fit(x_train, y_train)

Pipeline(steps=[('v', CountVectorizer()), ('nb', MultinomialNB())])

In [30]:
clf.score(x_test, y_test)

0.9838501291989664

In [41]:
clf.predict(some_emails)

array([0, 0, 0, 0])